### ISSUE TITLE
Feature toggle for notify send

### ISSUE THREAD

**Issue by wITTus** [daniel-e/stealthy#18]
Via compile-time feature toggle

**Comment by daniel-e** [comment]
Hi @wITTus,
what exactly are your requirements?

**Comment by wITTus** [comment]
notify-send does not work in non-gui, shell-only environments (e.g. VMs). In these environments an unnecessary error message gets printed. As the feature can't be implemented in these environments I suggest a feature toggle to disable it at compile-time.

**Comment by daniel-e** [comment]
You can now compile stealthy as follows to disable calls to notify-send:
cargo build --features "no_notify"
